CREATE TABLE `sf_user` (
  `jabber_id` varchar(256) NOT NULL,
  `password` varchar(256) NOT NULL,
  `first_name` varchar(256) DEFAULT NULL,
  `middle_name` varchar(256) DEFAULT NULL,
  `last_name` varchar(256) DEFAULT NULL,
  `nick_name` varchar(256) DEFAULT NULL,
  `email` varchar(256) NOT NULL,
  `contact_number` varchar(256) DEFAULT NULL,
  `gender` varchar(256) DEFAULT NULL,
  `bday` varchar(256) DEFAULT NULL,
  `avatar_base64_encoded` text,
  `avatar_mime_type` varchar(152) DEFAULT NULL,
  `address_home` text,
  `address_street` text,
  `address_locality` text,
  `address_state` text,
  `address_city` text,
  `address_country` text,
  `address_pcode` varchar(256) DEFAULT NULL,
  `description` text,
  `roster_version` int(11) NOT NULL DEFAULT '0',
  `status` tinyint(2) NOT NULL DEFAULT '1',
  `create_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`jabber_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
