package abs.ixi.server;

import abs.ixi.server.packet.Packet;
import abs.ixi.server.protocol.Protocol;

/**
 * Root interface for request validation
 */
public interface RequestValidation {
    /**
     * Validates packet and throws Error if validation fails
     * 
     * @param packet
     *            packet generated by {@link Protocol}
     * @param trigger
     *            the request string
     * @throws ValidationError
     *             its {@link RuntimeException}
     */
    public void validate(Packet packet, String trigger, Object... context) throws ValidationError;
}
