package abs.ixi.server.packet;

public enum XMPPError {
	INVALID_TO_ADDRESS(100),
	INVALID_FROM_ADDRESS(101),
	INTERNAL_SERVER(102),
	STANZA_TOO_BIG(103),
	BAD_FORMAT(104), 
	STREAM_HEADER_NOT_EXPECTED(105),
	AUTH_NOT_EXPECTED(106),
	IQ_NOT_EXPECTED(107),
	MESSAGE_NOT_EXPECTED(108),
	PRESENCE_NOT_EXPECTED(109),
	CHALLENGE_RESPONSE_NOT_EXPECTED(110),
	USER_REGISTRATION_NOT_EXPECTED(111),
	RESOURCE_BIND_NOT_EXPECTED(112),
	SESSION_EXPECTED(113),
	NOT_AUTHORISED(114),
	IMPROPER_ADDRESSING(115),
	UNSUPPORTED_ENCODING(116),
	UNSUPPORTED_VERSION(117),
	INVALID_XML(118),
	START_TLS_NOT_EXPECTED(119),
	ATTR_COUNT_LIMIT_EXCEEDED(120),
	ATTR_NAME_LENGTH_LIMIT_EXCEEDED(121),
	ATTR_VALUE_LENGTH_LIMIT_EXCEEDED(122),
	ELEMENT_NAME_SIZE_LIMIT_EXCEEDED(123),
	INVALID_AUTHZID(124),
	INVALID_MECHANISM(125),
	SASL_RESPONSE_NOT_EXPECTED(126),
	STREAM_MANAGEMENT_NOT_EXPECTED(127),
	STREAM_RESUME_NOT_EXPECTED(128), 
	ACK_REQUEST_NOT_EXPECTED(129), 
	ACK_NOT_EXPECTED(130);
	
	private int code;

	private XMPPError(int code) {
		this.code = code;
	}
	
	public int getCode(){
		return code;
	}
}